repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-ast
  - id: check-builtin-literals
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args: [--maxkb=1000]
  - id: detect-private-key
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout
- repo: https://github.com/hukkin/mdformat
  rev: 0.7.22
  hooks:
  - id: mdformat
    args: [--wrap=80, --number]
    additional_dependencies: [mdformat-gfm, mdformat-gfm-alerts, mdformat-tables, mdformat-config, mdformat-frontmatter, mdformat-footnote]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.10
  hooks:
  - id: ruff-check
    types_or: [ python, pyi ]
    args: [ --fix ]
  - id: ruff-format
    types_or: [ python, pyi ]
- repo: local
  hooks:
    - id: uv-lock
      name: uv-lock
      entry: uv lock
      language: system
      files: ^pyproject\.toml$
      pass_filenames: false
    - id: uv-export
      name: uv-export
      entry: uv export -o requirements.txt
      language: system
      always_run: true
      pass_filenames: false
- repo: local
  hooks:
    - id: check-py-types
      name: check-py-types
      entry: make check-py-types
      language: system
      pass_filenames: false
